In [1]:
import numpy as np
from numpy import linalg as LA
import cmath
from sage.combinat.designs.designs_pyx import is_orthogonal_array

V.<w> = CyclotomicField(5)

M5= MatrixSpace(V, 5,5)
M25= MatrixSpace(V, 25,25)
V25 = MatrixSpace(V, 1, 25)




Define Weyl-Heisenberg basis in dimension $d=5$:


In [2]:
# define matrices

Id25 = identity_matrix(25)
Id5 = identity_matrix(5)

X = M5([[0,1,0,0,0],[0,0,1,0,0], [0,0,0,1,0],[0,0,0,0,1], [1,0,0,0,0]])
Z =M5([[1,0,0,0,0],[0,w,0,0,0], [0,0,w**2,0,0], [0,0,0,w**3,0], [0,0,0,0, w**4]])

PowersOfX_neg = [Id5, X**(-1),  X**(-2), X**(-3), X**(-4)]
PowersOfZ = [Id5, Z, Z**2, Z**3, Z**4 ]

# define basis set

Basis = [Id5, X, Z, X**2, Z**2, X**3, Z**3, X**4, Z**4, X*Z, X*Z**2, X*Z**3,X*(Z**4), (X**2)*Z, (X**2)*Z**2, (X**2)*Z**3, (X**2)*(Z**4), (X**3)*Z, (X**3)*Z**2, (X**3)*Z**3, (X**3)*Z**4, (X**4)*Z, (X**4)*Z**2, (X**4)*Z**3, (X**4)*Z**4]

# define basis dictionary

Basis_dic = {0 : "Id4", 1 : "X", 2 : "Z", 3 : "X^2", 4 : "Z^2", 5 : "X^3", 6 : "Z^3", 7 : "X^4", 8 : "Z^4", 9: "XZ",  10 : "X Z^2", 11 : "XZ^3", 12 : "XZ^4", 13 : "X^2 Z", 14: " X^2 Z^2", 15 : "X^2 Z^3", 16 : "X^2 Z^4", 17: "X^3 Z", 18: "X^3 Z^2", 19: "X^3 Z^3", 20 : "X^3 Z^4", 21 : "X^4 Z", 22 : "X^4 Z^2", 23 : "X^4 Z^3", 24 : "X^4 Z^4" }

In [3]:
def unitV(i):
    vec = np.zeros(5)
    for l in range(0,5):
        if l == i:
            vec[l] = 1
    return vec

list = []
for i in range(0,5):
    list.append(vector(np.kron(unitV(i),unitV(i))))

psi = V25(sum(list))

In [4]:
# define diagonal basis

def phi(a,b):
    return ((PowersOfZ[a]*PowersOfX_neg[b]).tensor_product(Id5))*vector(psi)


# test 

matrix(np.array(phi(3,1)).reshape((5,5))) == (Z**3)*X**(-1)

True

In [5]:
sequence = np.array([1,
 w,
 -w^3 - w^2 - w - 1,
 -w^3 - w^2 - w - 1,
 w,
 w,
 w^2,
 1,
 1,
 w^2,
 -w^3 - w^2 - w - 1,
 1,
 w^3,
 w^3,
 1,
 -w^3 - w^2 - w - 1,
 1,
 w^3,
 w^3,
 1,
 w,
 w^2,
 1,
 1,
 w^2]).reshape((5,5))

list = []
for a1 in range(0,5):
    for a2 in range(0,5):
        #k = chinese_remainder(a1)[0]
        #l = chinese_remainder(a2)[0]
        #x = chinese_remainder(a1)[1]
        #y = chinese_remainder(a2)[1]
        list.append(sequence[a1,a2]*(phi(a1,a2).tensor_product(phi(a1,a2).conjugate())))


In [6]:
U = (1/5)*M25(sum(list)) # order 5

U.is_unitary()

True

In [7]:
print((U**5).str())

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0

Define left and right subalgebra of $\mathcal{M}_{25}(\mathbb{C})$:

In [10]:
L = [M25(Basis[i].tensor_product(Id5)) for i in range(0,25)]
R = [M25(Id5.tensor_product(Basis[i])) for i in range(0,25)]

LocalSubal = [L, R]

Define function that tests quasi-orthogonality:

In [11]:
def is_quasi_orth(A,B):
    for V in A:
            for W in B:
                K = V*W
                if (K.trace())/(K.nrows()) != ((V.trace())*(W.trace()))/((V.nrows())*(W.nrows())):
                    return false
    return true

Define function that tests if a subalgebra is delocalised:

In [12]:
def is_delocalised(A):
    for B in LocalSubal:
        if is_quasi_orth(A,B) == false:
            return false
            
    return true

Define function that tests if two subalgebras commute:

In [13]:
def commute(A,B):
    for a in A:
        for b in B:
            if a*b != b*a:
                return false
    return true
            

Define function that tests unitarity:

In [14]:
def is_unitary(A):
    return A*A.conjugate_transpose() == identity_matrix(A.nrows())

Define 5x5 block monomials, where the 1 is indexed by l and k:

In [15]:
def block(k,l,n):
    arr = np.zeros((n,n))
    arr[k-1,l-1] = 1
    return arr

# test

block(4,4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

Use two othogonal Latin squares in order to create 25 block monomials. Then: first merge them along the columns and then merge the resulting 5 blocks along the rows. This gives a 25x25 (2-unitary) permutation matrix.

In the following we will create multiple 2-unitaries using different orthogonal pairs of Latin squares. 

I.) Normal form

In [16]:
# normal form

# 11 34 25 53 42
# 43 22 54 15 31
# 52 45 33 21 14
# 35 51 12 44 23
# 24 13 41 32 55

# merge blocks along the columns

blockN1 = np.vstack((block(1,1,5),block(3,4,5), block(2,5,5), block(5,3,5), block(4,2,5)))

blockN2 = np.vstack((block(4,3,5),block(2,2,5), block(5,4,5), block(1,5,5), block(3,1,5)))

blockN3 = np.vstack((block(5,2,5),block(4,5,5), block(3,3,5), block(2,1,5), block(1,4,5)))

blockN4 = np.vstack((block(3,5,5),block(5,1,5), block(1,2,5), block(4,4,5), block(2,3,5)))

blockN5 = np.vstack((block(2,4,5),block(1,3,5), block(4,1,5), block(3,2,5), block(5,5,5)))

# merge blocks along the rows

U_N = M25(np.hstack((blockN1,blockN2, blockN3, blockN4, blockN5)))

print((U_N**2).str())

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0

In [17]:
# write matrix as permutation (for LaTeX)

perm = []
for i in range(0,25):
    for j in range(0,25):
        if U_N[j,i] == 1:
            perm.append(j)

            
perm

[0,
 23,
 19,
 7,
 11,
 22,
 6,
 3,
 14,
 15,
 16,
 4,
 12,
 20,
 8,
 9,
 10,
 21,
 18,
 2,
 13,
 17,
 5,
 1,
 24]

II.) Now consider the following 4 MOLS(5):

\begin{align}
{\displaystyle {K^1 = \ \begin{pmatrix}1&2&3&4&5\\2&3&4&5&1\\3&4&5&1&2\\4&5&1&2&3\\5&1&2&3&4\end{pmatrix}}\qquad {K^2 = \ \begin{pmatrix}1&2&3&4&5\\3&4&5&1&2\\5&1&2&3&4\\2&3&4&5&1\\4&5&1&2&3\end{pmatrix}}\qquad {K^3 = \begin{pmatrix}1&2&3&4&5\\5&1&2&3&4\\4&5&1&2&3\\3&4&5&1&2\\2&3&4&5&1\end{pmatrix}}\qquad {K^4 = \ \begin{pmatrix}1&2&3&4&5\\4&5&1&2&3\\2&3&4&5&1\\5&1&2&3&4\\3&4&5&1&2\end{pmatrix}}.}
\end{align}

II.I) $(K^1, K^2)$:

In [18]:
# merge blocks along the columns

block1 = np.vstack((block(1,1,5),block(2,2,5), block(3,3,5), block(4,4,5), block(5,5,5)))

block2 = np.vstack((block(2,3,5),block(3,4,5), block(4,5,5), block(5,1,5), block(1,2,5)))

block3 = np.vstack((block(3,5,5),block(4,1,5), block(5,2,5), block(1,3,5), block(2,4,5)))

block4 = np.vstack((block(4,2,5),block(5,3,5), block(1,4,5), block(2,5,5), block(3,1,5)))

block5 = np.vstack((block(5,4,5),block(1,5,5), block(2,1,5), block(3,2,5), block(4,3,5)))

# merge blocks along the rows

U_1 = M25(np.hstack((block1,block2, block3, block4, block5)))

II.II) $(K^1, K^3)$:

In [19]:
# merge blocks along the columns

block11 = np.vstack((block(1,1,5),block(2,2,5), block(3,3,5), block(4,4,5), block(5,5,5)))

block21 = np.vstack((block(2,5,5),block(3,1,5), block(4,2,5), block(5,3,5), block(1,4,5)))

block31 = np.vstack((block(3,4,5),block(4,5,5), block(5,1,5), block(1,2,5), block(2,3,5)))

block41 = np.vstack((block(4,3,5),block(5,4,5), block(1,5,5), block(2,1,5), block(3,2,5)))

block51 = np.vstack((block(5,2,5),block(1,3,5), block(2,4,5), block(3,5,5), block(4,1,5)))

# merge blocks along the rows

U_2 = M25(np.hstack((block11,block21, block31, block41, block51)))

II.III) $(K^1, K^4)$:

In [20]:
# merge blocks along the columns

block12 = np.vstack((block(1,1,5),block(2,2,5), block(3,3,5), block(4,4,5), block(5,5,5)))

block22 = np.vstack((block(2,4,5),block(3,5,5), block(4,1,5), block(5,2,5), block(1,3,5)))

block32 = np.vstack((block(3,2,5),block(4,3,5), block(5,4,5), block(1,5,5), block(2,1,5)))

block42 = np.vstack((block(4,5,5),block(5,1,5), block(1,2,5), block(2,3,5), block(3,4,5)))

block52 = np.vstack((block(5,3,5),block(1,4,5), block(2,5,5), block(3,1,5), block(4,2,5)))

# merge blocks along the rows

U_3 = M25(np.hstack((block12,block22, block32, block42, block52)))

II.IV) $(K^2, K^3)$:

In [21]:
# merge blocks along the columns

block13 = np.vstack((block(1,1,5),block(2,2,5), block(3,3,5), block(4,4,5), block(5,5,5)))

block23 = np.vstack((block(3,5,5),block(4,1,5), block(5,2,5), block(1,3,5), block(2,4,5)))

block33 = np.vstack((block(5,4,5),block(1,5,5), block(2,1,5), block(3,2,5), block(4,3,5)))

block43 = np.vstack((block(2,3,5),block(3,4,5), block(4,5,5), block(5,1,5), block(1,2,5)))

block53 = np.vstack((block(4,2,5),block(5,3,5), block(1,4,5), block(2,5,5), block(3,1,5)))

# merge blocks along the rows

U_4 = M25(np.hstack((block13,block23, block33, block43, block53)))

II.V) $(K^2, K^4)$:

In [22]:
# merge blocks along the columns

block14 = np.vstack((block(1,1,5),block(2,2,5), block(3,3,5), block(4,4,5), block(5,5,5)))

block24 = np.vstack((block(3,4,5),block(4,5,5), block(5,1,5), block(1,2,5), block(2,3,5)))

block34 = np.vstack((block(5,2,5),block(1,3,5), block(2,4,5), block(3,5,5), block(4,1,5)))

block44 = np.vstack((block(2,5,5),block(3,1,5), block(4,2,5), block(5,3,5), block(1,4,5)))

block54 = np.vstack((block(4,3,5),block(5,4,5), block(1,5,5), block(2,1,5), block(3,2,5)))

# merge blocks along the rows

U_5 = M25(np.hstack((block14,block24, block34, block44, block54)))

II.VI) $(K^3, K^4)$:

In [23]:
# merge blocks along the columns

block15 = np.vstack((block(1,1,5),block(2,2,5), block(3,3,5), block(4,4,5), block(5,5,5)))

block25 = np.vstack((block(5,4,5),block(1,5,5), block(2,1,5), block(3,2,5), block(4,3,5)))

block35 = np.vstack((block(4,2,5),block(5,3,5), block(1,4,5), block(2,5,5), block(3,1,5)))

block45 = np.vstack((block(3,5,5),block(4,1,5), block(5,2,5), block(1,3,5), block(2,4,5)))

block55 = np.vstack((block(2,3,5),block(3,4,5), block(4,5,5), block(5,1,5), block(1,2,5)))

# merge blocks along the rows

U_6 = M25(np.hstack((block15,block25, block35, block45, block55)))

Test unitarity of the created permutations:












In [24]:
U_list = [U_1, U_2, U_3, U_4, U_5, U_6]

for U in U_list:
    print(is_unitary(U))

True
True
True
True
True
True


Define delocalised subalgebras for each unitary:

In [25]:
# Define delocalised subalgebra

AL_1= [M25(U_1*L[i]*U_1.conjugate_transpose()) for i in range(0,25)]

AR_1= [M25(U_1*R[i]*U_1.conjugate_transpose()) for i in range(0,25)]


AL_2= [M25(U_2*L[i]*U_2.conjugate_transpose()) for i in range(0,25)]

AR_2= [M25(U_2*R[i]*U_2.conjugate_transpose()) for i in range(0,25)]


AL_3= [M25(U_3*L[i]*U_3.conjugate_transpose()) for i in range(0,25)]

AR_3= [M25(U_3*R[i]*U_3.conjugate_transpose()) for i in range(0,25)]


AL_4= [M25(U_4*L[i]*U_4.conjugate_transpose()) for i in range(0,25)]

AR_4= [M25(U_4*R[i]*U_4.conjugate_transpose()) for i in range(0,25)]


AL_5= [M25(U_5*L[i]*U_5.conjugate_transpose()) for i in range(0,25)]

AR_5= [M25(U_5*R[i]*U_5.conjugate_transpose()) for i in range(0,25)]



AL_6= [M25(U_6*L[i]*U_6.conjugate_transpose()) for i in range(0,25)]

AR_6= [M25(U_6*R[i]*U_6.conjugate_transpose()) for i in range(0,25)]


rotated_subal = [AL_1,AR_1, AL_2, AR_2, AL_3, AR_3, AL_4, AR_4, AL_5, AR_5, AL_6, AR_6]

rotated_subal_dic ={0: "AL_1", 1: "AR_1", 2: "AL_2", 3: "AR_2", 4: "AL_3", 5: "AR_3", 6: "AL_4", 7: "AR_4", 8: "AL_5", 9: "AR_5", 10: "AL_6", 11: "AR_6"}

Check if all subalgebras are delocalised:

In [26]:
for i in range(0, len(rotated_subal)):
    print(rotated_subal_dic[i], " ", is_delocalised(rotated_subal[i]))
        

AL_1   True
AR_1   True
AL_2   True
AR_2   True
AL_3   True
AR_3   True
AL_4   True
AR_4   True
AL_5   True
AR_5   True
AL_6   True
AR_6   True


Check if some of the subalgebras are equal and which one commute:

In [ ]:
for i in range(0, len(rotated_subal)):
    for j in range(0, len(rotated_subal)): 
        print( rotated_subal_dic[i], ",", rotated_subal_dic[j], " ", "Equality:", rotated_subal[i] == rotated_subal[j], " ",  "Commuting:",commute(rotated_subal[i], rotated_subal[j]),  " ", "Quasi-orthogonality:", is_quasi_orth(rotated_subal[i], rotated_subal[j]), "\n" )

            

AL_1 , AL_1   Equality: True   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_1   Equality: False   Commuting: True   Quasi-orthogonality: True 

AL_1 , AL_2   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_2   Equality: False   Commuting: False   Quasi-orthogonality: True 

AL_1 , AL_3   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_3   Equality: False   Commuting: False   Quasi-orthogonality: True 

AL_1 , AL_4   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_4   Equality: False   Commuting: True   Quasi-orthogonality: True 

AL_1 , AL_5   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_5   Equality: False   Commuting: False   Quasi-orthogonality: True 

AL_1 , AL_6   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_6   Equality: False   Commuting: True   Quasi-orthogonality: True 

AR_1 , AL_1   Equality: False   Commuting: True   

AL_5 , AL_5   Equality: True   Commuting: False   Quasi-orthogonality: False 

AL_5 , AR_5   Equality: False   Commuting: True   Quasi-orthogonality: True 

AL_5 , AL_6   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_5 , AR_6   Equality: False   Commuting: False   Quasi-orthogonality: True 

AR_5 , AL_1   Equality: False   Commuting: False   Quasi-orthogonality: True 

AR_5 , AR_1   Equality: False   Commuting: False   Quasi-orthogonality: False 

AR_5 , AL_2   Equality: False   Commuting: True   Quasi-orthogonality: True 

AR_5 , AR_2   Equality: True   Commuting: False   Quasi-orthogonality: False 

AR_5 , AL_3   Equality: False   Commuting: False   Quasi-orthogonality: True 

AR_5 , AR_3   Equality: False   Commuting: False   Quasi-orthogonality: False 

AR_5 , AL_4   Equality: False   Commuting: False   Quasi-orthogonality: True 

AR_5 , AR_4   Equality: False   Commuting: False   Quasi-orthogonality: False 

AR_5 , AL_5   Equality: False   Commuting: True   

In [108]:
quasi_orth_pairs = []

for i in range(0, len(rotated_subal)):
    for j in range(0, len(rotated_subal)):
         if is_quasi_orth(rotated_subal[i], rotated_subal[j]):
            quasi_orth_pairs.append([rotated_subal_dic[i], rotated_subal_dic[j]])

In [109]:
for element in quasi_orth_pairs:
    print(element[0], " ", element[1],  "\n")

AL_1   AR_1 

AL_1   AR_2 

AL_1   AR_3 

AL_1   AR_4 

AL_1   AR_5 

AL_1   AR_6 

AR_1   AL_1 

AR_1   AL_2 

AR_1   AL_3 

AR_1   AL_4 

AR_1   AL_5 

AR_1   AL_6 

AL_2   AR_1 

AL_2   AR_2 

AL_2   AR_3 

AL_2   AR_4 

AL_2   AR_5 

AL_2   AR_6 

AR_2   AL_1 

AR_2   AL_2 

AR_2   AL_3 

AR_2   AL_4 

AR_2   AL_5 

AR_2   AL_6 

AL_3   AR_1 

AL_3   AR_2 

AL_3   AR_3 

AL_3   AR_4 

AL_3   AR_5 

AL_3   AR_6 

AR_3   AL_1 

AR_3   AL_2 

AR_3   AL_3 

AR_3   AL_4 

AR_3   AL_5 

AR_3   AL_6 

AL_4   AR_1 

AL_4   AR_2 

AL_4   AR_3 

AL_4   AR_4 

AL_4   AR_5 

AL_4   AR_6 

AR_4   AL_1 

AR_4   AL_2 

AR_4   AL_3 

AR_4   AL_4 

AR_4   AL_5 

AR_4   AL_6 

AL_5   AR_1 

AL_5   AR_2 

AL_5   AR_3 

AL_5   AR_4 

AL_5   AR_5 

AL_5   AR_6 

AR_5   AL_1 

AR_5   AL_2 

AR_5   AL_3 

AR_5   AL_4 

AR_5   AL_5 

AR_5   AL_6 

AL_6   AR_1 

AL_6   AR_2 

AL_6   AR_3 

AL_6   AR_4 

AL_6   AR_5 

AL_6   AR_6 

AR_6   AL_1 

AR_6   AL_2 

AR_6   AL_3 

AR_6   AL_4 

AR_6   AL_5 

AR_6  

It follows: $A_{R_1} = A_{R_4} = A_{R_6}$ and $A_{R_2} = A_{R_5}$. What about $A_{R_3}$?

Check if subalgebras intersect:

In [103]:
intersection_list = []

for k in range(0, len(rotated_subal)):
    for j in range(0, len(rotated_subal)):
        i = 0
        for A in rotated_subal[k]:
            for B in rotated_subal[j]:
                if A == B:
                    i+=1
        intersection_list.append([rotated_subal_dic[k], rotated_subal_dic[j], i])

# print list

for element in intersection_list:
    print(element[0], ",", element[1], " ", element[2], "\n")

AL_1 , AL_1   25 

AL_1 , AR_1   1 

AL_1 , AL_2   5 

AL_1 , AR_2   1 

AL_1 , AL_3   5 

AL_1 , AR_3   1 

AL_1 , AL_4   25 

AL_1 , AR_4   1 

AL_1 , AL_5   5 

AL_1 , AR_5   1 

AL_1 , AL_6   25 

AL_1 , AR_6   1 

AR_1 , AL_1   1 

AR_1 , AR_1   25 

AR_1 , AL_2   1 

AR_1 , AR_2   5 

AR_1 , AL_3   1 

AR_1 , AR_3   5 

AR_1 , AL_4   1 

AR_1 , AR_4   25 

AR_1 , AL_5   1 

AR_1 , AR_5   5 

AR_1 , AL_6   1 

AR_1 , AR_6   25 

AL_2 , AL_1   5 

AL_2 , AR_1   1 

AL_2 , AL_2   25 

AL_2 , AR_2   1 

AL_2 , AL_3   5 

AL_2 , AR_3   1 

AL_2 , AL_4   5 

AL_2 , AR_4   1 

AL_2 , AL_5   25 

AL_2 , AR_5   1 

AL_2 , AL_6   5 

AL_2 , AR_6   1 

AR_2 , AL_1   1 

AR_2 , AR_1   5 

AR_2 , AL_2   1 

AR_2 , AR_2   25 

AR_2 , AL_3   1 

AR_2 , AR_3   5 

AR_2 , AL_4   1 

AR_2 , AR_4   5 

AR_2 , AL_5   1 

AR_2 , AR_5   25 

AR_2 , AL_6   1 

AR_2 , AR_6   5 

AL_3 , AL_1   5 

AL_3 , AR_1   1 

AL_3 , AL_2   5 

AL_3 , AR_2   1 

AL_3 , AL_3   25 

AL_3 , AR_3   1 

AL_3 , AL_4   5 


So $A_{R_3}$ has a non trivial intersection with any of the other $A_{R}$'s