In [1]:
import numpy as np
from numpy import linalg as LA
import cmath
from sage.combinat.designs.designs_pyx import is_orthogonal_array

V.<l> = CyclotomicField(4)

K.<d> = CyclotomicField(4)

M2= MatrixSpace(K, 2,2)
M4= MatrixSpace(V, 4,4)
M16= MatrixSpace(V, 16,16)




In [2]:
Id16 = identity_matrix(16)
Id2 = identity_matrix(2)
Id4 = identity_matrix(4)
Id8 = identity_matrix(8)
X = M4([[0,1,0,0],[0,0,1,0], [0,0,0,1], [1,0,0,0]])
Z =M4([[1,0,0,0],[0,l,0,0], [0,0,l**2,0], [0,0,0,l**3]])




X_2 = M2([[0,1],[1,0]])
Z_2 = M2([[1,0],[0,-1]])

Basis2 = [Id2, X_2, Z_2, X_2*Z_2]

Basis = [Id4, X, Z, X**2, Z**2, X**3, Z**3, X*Z, X*Z**2, X*Z**3, (X**2)*Z, (X**2)*Z**2, (X**2)*Z**3, (X**3)*Z, (X**3)*Z**2, (X**3)*Z**3]

Basis_dic = {0 : "Id4", 1 : "X", 2 : "Z", 3 : "X^2", 4 : "Z^2", 5 : "X^3", 6 : "Z^3", 7 : "XZ", 8 : "S Z^2", 9 : "XZ^3", 10: "X^2 Z", 11: " X^2 Z^2", 12 : "X^2 Z^3", 13: "X^3 Z", 14: "X^3 Z^2", 15: "X^3 Z^3" }

In [3]:
len(Basis)

16

In [4]:
L = [M16((X**3).tensor_product(Id4)), M16((Z**3).tensor_product(Id4)),M16((X*Z**3).tensor_product(Id4)), M16(((X**3)*Z).tensor_product(Id4)),M16(((X**3)*Z**3).tensor_product(Id4)), M16(((X**2)*Z**3).tensor_product(Id4)) , M16(((X**3)*(Z**2)).tensor_product(Id4)),M16((X**2).tensor_product(Id4)), M16((Z**2).tensor_product(Id4)),M16((X*Z**2).tensor_product(Id4)), M16(((X**2)*Z).tensor_product(Id4)),M16(((X**2)*Z**2).tensor_product(Id4)), X.tensor_product(Id4) , M16(Z.tensor_product(Id4)),M16((X*Z).tensor_product(Id4)), M16(Id16) ]

R = [M16(Id4.tensor_product(Basis[i])) for i in range(0,16)  ]

R_2 = [M16(Id8.tensor_product(Basis2[i])) for i in range(0,4)  ]

L_2 = [M16(Basis2[i].tensor_product(Id8)) for i in range(0,4)  ]

M1 = [M16(Id2.tensor_product(Basis2[i].tensor_product(Id4))) for i in range(0,4)  ]

M2 = [M16(Id4.tensor_product(Basis2[i].tensor_product(Id2))) for i in range(0,4)  ]

LocalSubal = [L, R]

LocalSubal_2 = [L_2, R_2, M1, M2]

In [5]:
def is_quasi_orth(A,B):
    for V in A:
            for W in B:
                K = V*W
                if (K.trace())/(K.nrows()) != ((V.trace())*(W.trace()))/((V.nrows())*(W.nrows())):
                    return false
    return true


is_quasi_orth(L_2,AM_N)

NameError: name 'AM_N' is not defined

In [ ]:
def is_unitary(A):
    return A*A.conjugate_transpose() == identity_matrix(A.nrows())

In [6]:
def is_delocalised(A,O):
    for N in O:
        if is_quasi_orth(A,N) == false:
            return false
    return true



In [7]:
def commute(A,B):
    for a in A:
        for b in B:
            if a*b != b*a:
                return false
    return true
            

In [8]:
# Define ququad basis

def unitV(i):
    vec = np.zeros(4)
    for l in range(0,4):
        if l == i:
            vec[l] = 1
    return vec

# Test 

unitV(0)

# Define tensor product of 2 ququats

def unitV2(i,k):
    return np.kron(unitV(i), unitV(k))


# Test 

unitV2(3,3)

# 

def unitV16(i):
    vec = np.zeros(16)
    for l in range(0,16):
        if l == i:
            vec[l] = 1
    return vec

unitV16(1)

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# define 4x4 block monomials where the 1 is index by l and k 

def block(k,l,n):
    arr = np.zeros((n,n))
    arr[k-1,l-1] = 1
    return arr
block(4,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [19]:
# merge the blocks along columns
 # I. & II., U_N
block1 = np.vstack((block(1,1,4),block(2,2,4), block(3,3,4), block(4,4,4)))

block2 = np.vstack((block(2,4,4), block(1,3,4),  block(4,2,4),  block(3,1,4)))

block3 = np.vstack((block(3,2,4), block(4,1,4), block(1,4,4),  block(2,3,4)))

block4 = np.vstack((block(4,3,4), block(3,4,4), block(2,1,4), block(1,2,4)))

In [20]:
# I. & III., U_2_1

block11 = np.vstack((block(1,1,4),block(2,2,4), block(3,3,4), block(4,4,4)))

block21 = np.vstack((block(2,3,4), block(1,4,4),  block(4,1,4),  block(3,2,4)))

block31 = np.vstack((block(3,4,4), block(4,3,4), block(1,2,4),  block(2,1,4)))

block41 = np.vstack((block(4,2,4), block(3,1,4), block(2,4,4), block(1,3,4)))

In [21]:
# II. & III., U_2_2

block12 = np.vstack((block(1,1,4),block(2,2,4), block(3,3,4), block(4,4,4)))

block22 = np.vstack((block(4,3,4), block(3,4,4),  block(2,1,4),  block(1,2,4)))

block32 = np.vstack((block(2,4,4), block(1,3,4), block(4,2,4),  block(3,1,4)))

block42 = np.vstack((block(3,2,4), block(4,1,4), block(1,4,4), block(2,3,4)))

In [22]:
# construct another 2 unitary of order 2

block1_1 = np.vstack((block(1,1,4),block(4,3,4), block(2,4,4), block(3,2,4)))
block2_1 = np.vstack((block(3,4,4), block(2,2,4),  block(4,1,4),  block(1,3,4)))

block3_1 = np.vstack((block(4,2,4), block(1,4,4), block(3,3,4),  block(2,1,4)))

block4_1 = np.vstack((block(2,3,4), block(3,1,4), block(1,2,4), block(4,4,4)))

In [23]:
U_2_1 = M16(np.hstack((block11,block21, block31, block41)))

# 12 rearrangements are unitary for 2**4, ORDER 15
U_2_2 = M16(np.hstack((block12,block22, block32, block42)))

In [24]:
U_2_2**15

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

Next we give a collection of 2-unitaries in dimension 16. 




In [25]:
# normal form, has order 5
U_N = M16(np.hstack((block1,block2, block3, block4)))

# 11 24 32 43
# 22 13 41 34
# 33 42 14 21
# 44 31 23 12

# 4 rearrangements for 2**4 are unitary

# order 6
U = M16(np.array([unitV2(0,0),unitV2(1,1), unitV2(2,2), unitV2(3,3), unitV2(1,3), unitV2(0,2), unitV2(3,1), unitV2(2,0), unitV2(2,1), unitV2(3,0), unitV2(0,3), unitV2(1,2), unitV2(3,2), unitV2(2,3), unitV2(1,0), unitV2(0,1)]))

# 11 22 33 44
# 23 14 41 32
# 34 43 12 21
# 42 31 24 13

# 6 rearrangements for 2**4 are unitary

# order 8

Up = M16([[1,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,-1], [0,1,0,0,-1,0,0,0,0,0,0,-1,0,0,-1,0],[0,0,-1,0,0,0,0,1,-1,0,0,0,0,-1,0,0],
          [0,0,0,-1,0,0,1,0,0,1,0,0,1,0,0,0],[0,1,0,0,-1,0,0,0,0,0,0,1,0,0,1,0],[-1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,-1],
          [0,0,0,-1,0,0,1,0,0,-1,0,0,-1,0,0,0],[0,0,-1,0,0,0,0,-1,1,0,0,0,0,-1,0,0], [0,0,-1,0,0,0,0,-1,-1,0,0,0,0,1,0,0],
          [0,0,0,1,0,0,1,0,0,-1,0,0,1,0,0,0],[-1,0,0,0,0,-1,0,0,0,0,-1,0,0,0,0,-1], [0,-1,0,0,-1,0,0,0,0,0,0,-1,0,0,1,0],
          [0,0,0,-1,0,0,-1,0,0,-1,0,0,1,0,0,0], [0,0,1,0,0,0,0,-1,-1,0,0,0,0,-1,0,0], [0,1,0,0,1,0,0,0,0,0,0,-1,0,0,1,0],
          [1,0,0,0,0,-1,0,0,0,0,1,0,0,0,0,-1]])

# no rearrangement for 2**4 is unitary

#print(U.str())
U_N**5

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

In [26]:

def Bell_basis(d):
    K.<w> = CyclotomicField(d)
    V = MatrixSpace(K, 1, d**2)
    L = []
    for i in range(0,d):
        L.append(vector(np.kron(unitV(i),unitV(i))))
    return V(sum(L))

Bell_basis(4)

[1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]

In [27]:
# order 2

U_2 = M16([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
  ])

# 12 rearrangements for 2**4 are unitary


# write matrix as permutation (for LaTeX)

perm = []
for i in range(0,16):
    for j in range(0,16):
        if U_2[j,i] == 1:
            perm.append(j)

            
perm

[0, 11, 13, 6, 14, 5, 3, 8, 7, 12, 10, 1, 9, 2, 4, 15]

In [32]:
(U_2.conjugate_transpose())*Bell_basis(4).conjugate_transpose() == Bell_basis(4).conjugate_transpose()

True

In [130]:
#is_unitary((1/2)*Up)

is_unitary(U_2)

True

In [131]:
U_2 == U_2.transpose()

True

In [132]:
U_2**2

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

In [133]:
((1/2)*Up)**8

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

In [134]:
# New 2-unitary

H2 = matrix([[1,1],[1,-1]])

F4 = (1/2)*matrix([[1,1,1,1],[1,l, l**2, l**3], [1,l**2, l**4, l**6], [1,l**3, l**6, l**9]])

F = F4.tensor_product(Id4)

# controlled CNOT gate
arr = []
for i in range(0,4):
    arr.append(M4(vector(unitV(i)).tensor_product(vector(unitV(i)))).tensor_product(M4(X**i)))

CNOT = matrix(sum(arr))


Unew = M16((H2.tensor_product(H2.tensor_product(Id4)))*Up)

Lambda = M16(F.conjugate_transpose()*CNOT.conjugate_transpose()*Unew*CNOT*F)

CHM = M16(F.conjugate_transpose()*Unew*F)

#is_unitary((1/4)*Unew)

# order

#MatrixGroup(Unew*(1/4)).order()

# to do construct quantum latin square out of this and check if genuinly quantum
Unew**4

[  24  -56  -72   56   -8   24   -8  -72  -72 -104 -120    8    8  -88   40  -88]
[  40   -8 -120  -40  136   24   -8   56   24  104  -72   40   24   -8   72   40]
[  56  -72   24   -8  -40   88  -88   40  -72   24   24  104 -104   88   24  -40]
[  88  104   40   56  -24  -24  -24  104  -72   40  -40   40  104  -24  -72  -56]
[  24  168  -40   -8   24   56   56   -8   -8  -72   72   72  -88  -56   40    8]
[  24  -24   88  168   88   72   72    8  -24   -8    8  -40    8   40   56   56]
[ -72   56  -40   -8 -104   24  104  -24  -72   88  -40  -24   24   88   88  -40]
[ -24   24  -40    8   24 -104  -40   88 -120  -40  -24 -104 -104   24    8   56]
[  56  -56   24  -72  -40   24   88  152   56  -72    8  -56    8  -24   72  -56]
[-152  -40   40  -40   40   56   -8   56 -104    8   56   40   56 -104    8    8]
[ -88   40   40  -24  104   40   24   24   40  -24  -88   -8  -56   72  -88 -120]
[ -88   24   24  104  -40  -72  -72   56  104   24  -24   56  -40  -40  104  -40]
[  24   40   -8 

In [135]:
is_unitary((1/2)*(H2.tensor_product(H2)))

True

In [136]:
H = H2.tensor_product(H2.tensor_product(Id4))
 
Uneww = M16((H2.tensor_product(H2.tensor_product(Id4)))*Up*(H2.tensor_product(H2.tensor_product(Id4))).conjugate_transpose())

In [137]:
(1/8)*Uneww*(Uneww.conjugate_transpose())

[8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8]

In [138]:
Uneww

[ 0  2 -2 -2  0 -2 -2  2  0  2 -2 -2  4  2  2 -2]
[-2  0  2 -2 -2  0  2  2 -2  4  2  2  2  0 -2  2]
[-2 -2  0 -2 -2  2 -4 -2  2  2  0  2 -2  2  0 -2]
[ 2 -2  2 -4  2  2 -2  0 -2 -2 -2  0  2 -2 -2  0]
[ 0  2 -2 -2  0 -2 -2  2  4 -2  2  2  0 -2 -2  2]
[ 2  0 -2  2  2  0 -2 -2 -2  0  2  2  2  4 -2  2]
[-2 -2 -4  2 -2  2  0  2 -2 -2  0  2  2 -2  0 -2]
[-2  2  2  0 -2 -2 -2 -4 -2 -2  2  0  2 -2  2  0]
[ 0  2  2  2  4  2 -2  2  0  2  2  2  0 -2  2 -2]
[-2  4 -2 -2  2  0  2 -2 -2  0 -2  2 -2  0 -2 -2]
[-2 -2  0  2  2 -2  0 -2  2  2  0 -2  2 -2 -4 -2]
[ 2  2 -2  0 -2  2 -2  0 -2  2  2 -4 -2 -2 -2  0]
[ 4 -2 -2 -2  0 -2  2 -2  0  2  2  2  0 -2  2 -2]
[-2  0 -2 -2  2  4  2 -2  2  0  2 -2  2  0  2  2]
[ 2  2  0  2 -2  2  0 -2  2  2 -4  2  2 -2  0  2]
[ 2  2  2  0 -2  2  2  0  2 -2  2  0  2  2 -2 -4]

In [139]:
#listOfGen = []
#for V in MatrixSpace(GF(3),4,4).list():
    #if is_unitary(V):
        #listOfGen.append(V)
        
#U4 = MatrixGroup(listOfGen).list()

U4 = GU(4, 2)

U4.list()



KeyboardInterrupt: 

In [ ]:
for i in range(0,20):
    W = M2([[0,-l^(i)], [l^(-i),0]])
    U = (W.tensor_product(W)).tensor_product(W.tensor_product(W))


    print(MatrixGroup(U*(Unew*(1/4))*U.conjugate_transpose()).order())
     

In [38]:
od

+Infinity

Find new 2-unitary according to transformation given in Goyeneche's paper 

In [140]:
list = []
for i in range(0,4):
    for j in range(0,4):
        for k in range(0,4):
            for r in range(0,4):
                t = j*(i-k)+r*(i+k)
                #t = i*(j+r+k)
                list.append(l**t)
                #V[i,j,k,r] = l**t

Uconstr = M16(np.array(list).reshape((16,16)))
is_unitary(Uconstr)



False

In [49]:
# Construct quantum latin square

psi_list = []

for i in range(0,4):
    for j in range(0,4):
        psi_list.append(matrix(Up*(1/2))*vector(np.kron(unitV(i),unitV(j))))
        

    

In [50]:
for i in range(0,16):
    print(psi_list[i])


(0.5, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, 0.5)
(0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.5, 0.0)
(0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, -0.5, -0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0)
(0.0, 0.0, 0.0, -0.5, 0.0, 0.0, -0.5, 0.0, 0.0, 0.5, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0)
(0.0, -0.5, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.5, 0.0)
(0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, -0.5)
(0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0)
(0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, -0.5, -0.5, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0)
(0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, 0.5, -0.5, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0)
(0.0, 0.0, 0.0, 0.5, 0.0, 0.0, -0.5, 0.0, 0.0, -0.5, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0)
(-0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 0.0, 0.5)
(0.0, -0.5, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, -0.5, 0.0)

In [51]:
# construct density matrix

def densityMatrix(vec):
        M = np.zeros((4,4,4,4))
        for i in range(0,4):
            for j in range(0,4):
                for k in range(0,4):
                    for l in range(0,4):
                        M[i,j,k,l] = vector(np.kron(unitV(i), unitV(j)))*matrix(np.outer(vec,vec))*vector(np.kron(unitV(k), unitV(l)))
        return M
            


In [52]:
M = densityMatrix(psi_list[1])

In [53]:
# check entanglement

# partial trace

M_red = []
for i in range(0,4):
    for j in range(0, 4):
        for k in range(0,4):
            for l in range(0,4):
                M_red.append(M[i,j,k,l]*matrix(np.outer(unitV(i), unitV(k)))*np.trace(np.outer(unitV(j), unitV(l))))

In [54]:
# trace of subsystem

np.trace(matrix(sum(M_red))**2)

0.25

In [669]:
Unew

[ 1  1 -1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1  1 -1]
[-1  1  1  1 -1  1  1 -1 -1 -1  1 -1  1 -1 -1 -1]
[-1  1 -1 -1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1]
[ 1 -1 -1 -1 -1 -1  1 -1  1  1  1 -1  1 -1  1 -1]
[ 1 -1 -1  1  1  1  1 -1 -1  1 -1 -1 -1  1 -1 -1]
[ 1  1 -1  1 -1 -1  1  1  1 -1 -1 -1  1  1 -1  1]
[-1 -1 -1  1 -1 -1 -1  1 -1  1 -1  1  1 -1 -1 -1]
[-1 -1  1 -1 -1  1  1  1 -1  1 -1 -1  1  1  1  1]
[ 1  1  1  1 -1  1  1  1  1  1 -1  1 -1 -1  1 -1]
[-1  1 -1 -1 -1  1 -1  1  1  1  1 -1 -1  1 -1 -1]
[ 1 -1 -1 -1 -1  1  1  1 -1 -1  1  1 -1 -1 -1  1]
[-1  1 -1 -1  1  1  1 -1  1  1 -1  1  1 -1 -1  1]
[ 1 -1  1 -1  1  1 -1  1  1 -1 -1 -1  1 -1 -1 -1]
[ 1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1]
[ 1  1 -1  1  1  1 -1  1 -1  1  1 -1  1 -1  1  1]
[ 1  1  1 -1  1 -1  1  1 -1  1  1  1  1  1 -1 -1]

In [675]:
UT = np.array((1/4)*Unew).reshape((4,4,4,4))

# Construct all possible rearrangements of the entries of U'
# I. e. partion the set of 6 indices into two sets of 3 indices


U_R_1 = np.zeros((16,16))
U_R_2 = np.zeros((16,16))
U_G_1 = np.zeros((16,16))
U_G_2 = np.zeros((16,16))




for i in range(0,4):
    for j in range(0,4):
        for k in range(0,4):
            for l in range(0,4):
                        a = 4*i + j 
                        b = 4*l + k
                        U_R_1[a,b] = UT[l,j,k,i] # {6,2,3} U {4,5,1}  
                        
                        U_R_2[a,b] = UT[i,k,j,l] # {5,2,3} U {4,1,6}
                    
                        U_G_1[a,b] = UT[k,j,i,l] # {4,2,3} U {1,5,6}
                        
                        U_G_2[a,b] = UT[i,l,k,j] # {1,4,3} U {2,5,6}
                        
                        
rearr = [U_R_1,U_R_2,U_G_1,U_G_2]

U_rearr = [Matrix(V) for V in rearr]



In [141]:
# 4-unitary?

UT = np.array(Up).reshape((2,2,2,2,2,2,2,2))

# Construct all possible rearrangements of the entries of U'
# I. e. partion the set of 6 indices into two sets of 3 indices


U_R_1 = np.zeros((2,2,2,2,2,2,2,2))
U_R_2 = np.zeros((2,2,2,2,2,2,2,2))
U_G_1 = np.zeros((2,2,2,2,2,2,2,2))
U_G_2 = np.zeros((2,2,2,2,2,2,2,2))

U_R_3 = np.zeros((2,2,2,2,2,2,2,2))
U_R_4 = np.zeros((2,2,2,2,2,2,2,2))
U_G_3 = np.zeros((2,2,2,2,2,2,2,2))
U_G_4 = np.zeros((2,2,2,2,2,2,2,2))

U_R_5 = np.zeros((2,2,2,2,2,2,2,2))
U_R_6 = np.zeros((2,2,2,2,2,2,2,2))
U_R_7 = np.zeros((2,2,2,2,2,2,2,2))
U_R_8 = np.zeros((2,2,2,2,2,2,2,2))
U_R_9 = np.zeros((2,2,2,2,2,2,2,2))
U_R_10 = np.zeros((2,2,2,2,2,2,2,2))
U_R_11 = np.zeros((2,2,2,2,2,2,2,2))
U_R_12 = np.zeros((2,2,2,2,2,2,2,2))




for i in range(0,2):
    for j in range(0,2):
        for k in range(0,2):
            for l in range(0,2):
                for m in range(0,2):
                    for n in range(0,2):
                        for o in range(0,2):
                            for p in range(0,2):
                                U_R_1[i,j,k,l,m,n,o,p] = UT[n,j,k,l,m,i,o,p] # {6,2,3} U {4,5,1}  
                        
                                U_R_2[i,j,k,l,m,n,o,p] = UT[o,j,k,l,m,n,i,p] # {5,2,3} U {4,1,6}
                    
                                U_R_3[i,j,k,l,m,n,o,p] = UT[p,j,k,l,m,n,o,i] # {4,2,3} U {1,5,6}
                        
                                U_R_4[i,j,k,l,m,n,o,p] = UT[i,m,k,l,j,n,o,p] # {6,2,3} U {4,5,1}  
                        
                                U_R_5[i,j,k,l,m,n,o,p] = UT[i,o,k,l,m,n,j,p] # {5,2,3} U {4,1,6}
                    
                                U_R_6[i,j,k,l,m,n,o,p] = UT[i,p,k,l,m,n,o,j] # {4,2,3} U {1,5,6}
                                
                                U_R_7[i,j,k,l,m,n,o,p] = UT[i,j,m,l,k,n,o,p] # {6,2,3} U {4,5,1}  
                        
                                U_R_8[i,j,k,l,m,n,o,p] = UT[i,j,n,l,m,k,o,p] # {5,2,3} U {4,1,6}
                    
                                U_R_9[i,j,k,l,m,n,o,p] = UT[i,j,p,l,m,n,o,k] # {4,2,3} U {1,5,6}
                        
                                U_R_10[i,j,k,l,m,n,o,p] = UT[i,j,k,m,l,n,o,p] # {6,2,3} U {4,5,1}  
                        
                                U_R_11[i,j,k,l,m,n,o,p] = UT[i,j,k,n,m,l,o,p] # {5,2,3} U {4,1,6}
                    
                                U_R_12[i,j,k,l,m,n,o,p] = UT[i,j,k,o,m,n,l,p] # {4,2,3} U {1,5,6}
                        
                                U_G_1[i,j,k,l,m,n,o,p] = UT[m,j,k,l, i, n, o ,p] # {1,4,3} U {2,5,6}
                                
                                U_G_2[i,j,k,l,m,n,o,p] = UT[i,n,k,l, m, j, o ,p] # {1,4,3} U {2,5,6}
                                
                                U_G_3[i,j,k,l,m,n,o,p] = UT[i,j,o,l, m, n, k ,p] # {1,4,3} U {2,5,6}
                                
                                U_G_4[i,j,k,l,m,n,o,p] = UT[i,j,k,p, m, n, o ,l] # {1,4,3} U {2,5,6}
                        
                        
rearr = [U_R_1,U_R_2,U_R_3,U_R_4,U_R_5,U_R_6,U_R_7,U_R_8,U_R_9,U_R_10,U_R_11,U_R_12,U_G_1,U_G_2, U_G_3,U_G_4 ]

U_rearr = [Matrix(np.array(V).reshape((16,16))) for V in rearr]


In [142]:
# Test if all rearrangements are unitary

for V in U_rearr:
    print(is_unitary(V))

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [144]:
# Define delocalised subalgebra

AL_2= [M16(U_2_2*L[i]*U_2_2.conjugate_transpose()) for i in range(0,16)]

AL_1= [M16(U_2_1*L[i]*U_2_1.conjugate_transpose()) for i in range(0,16)]


AR_1= [M16(U_2_1*R[i]*U_2_1.conjugate_transpose()) for i in range(0,16)]

AR_2= [M16(U_2_2*R[i]*U_2_2.conjugate_transpose()) for i in range(0,16)]



AL_N= [M16(Up*L_2[i]*Up.conjugate_transpose()) for i in range(0,4)]


AR_N= [M16(Up*R_2[i]*Up.conjugate_transpose()) for i in range(0,4)]

AM1_N= [M16(Up*M1[i]*Up.conjugate_transpose()) for i in range(0,4)]

AM2_N= [M16(Up*M2[i]*Up.conjugate_transpose()) for i in range(0,4)]


rotated_subal = [AL_1, AL_2, AL_N, AR_1, AR_2, AR_N]

rotated_subal_2 = [ AL_N, AR_N, AM1_N, AM2_N]

rotated_subal_dic = {0 : "AL_1", 1 : "AL_2", 2 : "AL_N", 3: "AR_1", 4: "AR_2", 5: "AR_N"}

# Test if all subalgebras are delocalised

for A in rotated_subal_2:
    print(is_delocalised(A, LocalSubal_2))

True
True
True
True


In [134]:
quasi_orth_pairs = []

for i in range(0, len(rotated_subal)):
    for j in range(0, len(rotated_subal)):
        print(rotated_subal_dic[i], ",", rotated_subal_dic[j], " ", "Equality:", rotated_subal[i] == rotated_subal[j], " ",  "Commuting:",commute(rotated_subal[i], rotated_subal[j]),  " ", "Quasi-orthogonality:", is_quasi_orth(rotated_subal[i], rotated_subal[j]), "\n")
        if is_quasi_orth(rotated_subal[i], rotated_subal[j]):
            quasi_orth_pairs.append([rotated_subal_dic[i], rotated_subal_dic[j]])
            

AL_1 , AL_1   Equality: True   Commuting: False   Quasi-orthogonality: False 

AL_1 , AL_2   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AL_N   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_1 , AR_1   Equality: False   Commuting: True   Quasi-orthogonality: True 

AL_1 , AR_2   Equality: False   Commuting: False   Quasi-orthogonality: True 

AL_1 , AR_N   Equality: False   Commuting: False   Quasi-orthogonality: True 

AL_2 , AL_1   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_2 , AL_2   Equality: True   Commuting: False   Quasi-orthogonality: False 

AL_2 , AL_N   Equality: False   Commuting: False   Quasi-orthogonality: False 

AL_2 , AR_1   Equality: False   Commuting: False   Quasi-orthogonality: True 

AL_2 , AR_2   Equality: False   Commuting: True   Quasi-orthogonality: True 

AL_2 , AR_N   Equality: False   Commuting: True   Quasi-orthogonality: True 

AL_N , AL_1   Equality: False   Commuting: False   

In [135]:
for element in quasi_orth_pairs:
    print(element[0], " ", element[1],  "\n")

AL_1   AR_1 

AL_1   AR_2 

AL_1   AR_N 

AL_2   AR_1 

AL_2   AR_2 

AL_2   AR_N 

AL_N   AR_1 

AL_N   AR_2 

AL_N   AR_N 

AR_1   AL_1 

AR_1   AL_2 

AR_1   AL_N 

AR_2   AL_1 

AR_2   AL_2 

AR_2   AL_N 

AR_N   AL_1 

AR_N   AL_2 

AR_N   AL_N 



In [ ]:
node = []
for element1 in quasi_orth_pairs:
    for element2 in quasi_orth_pairs:
        if element1[0] == element2[0]:
            node.append(element2[1])
            

In [129]:
i = 0

for A in AL_N:
    for B in AL_2:
        if A ==B:
            i+=1

i

1

In [128]:
AL_N == AL_2

False

In [105]:
AL_dic = []

for M in AL_2:
    for j in range(0,len(Basis)):
        for k in range(0,len(Basis)):
            if M == Basis[j].tensor_product(Basis[k]):
                    AL_dic.append([Basis_dic[j], Basis_dic[k]])
            
            



In [130]:
flag = true

for A in AL_2:
    for B in AL_N:
        if (A*B != B*A):
            flag = false
            
flag

False

In [104]:
for M in AL_dic:
    print(M[0], M[1], "\n")

Id4 Id4 

X^2 X^2 



In [636]:
# 2**4 system
Id8 = identity_matrix(8)
Id2 = identity_matrix(2)
X = M2([[0,1],[1,0]])
Z =M2([[1,0],[0,-1]])

Basis = [Id2, X, Z, X*Z]

In [109]:
L = [M16(X_2.tensor_product(Id8)), M16(Z_2.tensor_product(Id8)), M16((X*Z).tensor_product(Id8)), M16(Id16)]

R = [M16(Id8.tensor_product(X)), M16(Id8.tensor_product(Z)), M16(Id8.tensor_product(X*Z)), M16(Id16)]

M1 = [M16(Id2.tensor_product(X.tensor_product(Id4))), M16(Id2.tensor_product(Z.tensor_product(Id4))), M16(Id2.tensor_product((X*Z).tensor_product(Id4))), M16(Id16)]

M2 = [M16(Id4.tensor_product(X.tensor_product(Id2))), M16(Id4.tensor_product(Z.tensor_product(Id2))), M16(Id4.tensor_product((X*Z).tensor_product(Id2))), M16(Id16)]

LocalSubal = [L, R, M1, M2]

ValueError: inconsistent number of rows: should be 16 but got 32

In [108]:
# Define delocalised subalgebra

AL= [M16(Up*L[i]*Up.conjugate_transpose()) for i in range(0,4)]

AR= [M16(Up*R[i]*Up.conjugate_transpose()) for i in range(0,4)]

AM1= [M16(Up*M1[i]*Up.conjugate_transpose()) for i in range(0,4)]

AM2= [M16(Up*M2[i]*Up.conjugate_transpose()) for i in range(0,4)]

rotated_subal = [AL,AR, AM1, AM2]

# Test if all subalgebras are delocalised

for A in rotated_subal:
    print(is_delocalised(A, LocalSubal_2))

True
True
True
True
