In [120]:
import numpy as np

I) Functions

In the following section the fields, the matrix spaces and some of the elementary functions that are used throughtout this notebook will be defined. 

In [64]:
# define fields and matrix spaces

V.<l> = CyclotomicField(2)
K.<w> = CyclotomicField(3)

M3= MatrixSpace(K, 3,3)
M9= MatrixSpace(K, 9,9)
M27 = MatrixSpace(K, 27,27)


M2 =MatrixSpace(V, 2,2)
M4 =MatrixSpace(V, 4,4)
M8 =MatrixSpace(V, 8,8)

In [65]:
# Define a function that checks if two subalgebras are quasi-orthogonal

def is_quasi_orth(A,B):
    for V in A:
        for W in B:
            K = V*W
            if (K.trace())/(K.nrows()) != ((V.trace())*(W.trace()))/((V.nrows())*(W.nrows())):
                return false
    return true

In [66]:
# Define a function that checks if a subalgebra is delocalised

def is_delocalised(A,List):
    for element in List:
        if is_quasi_orth(A,element) == false:
            return false
    return true
            

Define all possible reorderings of a 6-valent tensor as functions. This results in 9 functions:

In [67]:
# partial transpose [l,j,k,i,m,n]

def matrix_partial_transpose_14(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[l,j,k,i,m,n] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [68]:
# partial transpose [i,m,k,l,j,n]

def matrix_partial_transpose_25(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[i,m,k,l,j,n] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [69]:
# partial transpose [i,j,n,l,m,k]

def matrix_partial_transpose_36(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[i,j,n,l,m,k] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [57]:
# reshuffle [n,j,k,l,m,i]

def matrix_reshuffle_16(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[n,j,k,l,m,i] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [38]:
# reshuffle [m,j,k,l,i,n]

def matrix_reshuffle_15(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[m,j,k,l,i,n] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [39]:
# reshuffle [i,l,k,j,m,n]

def matrix_reshuffle_24(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[i,l,k,j,m,n] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [40]:
# reshuffle [i,n,k,l,m,j]

def matrix_reshuffle_26(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[i,n,k,l,m,j] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [41]:
# reshuffle [i,j,l,k,m,n]

def matrix_reshuffle_34(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[i,j,l,k,m,n]for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


In [42]:
# reshuffle [i,j,m,l,k,n]

def matrix_reshuffle_35(M,d):
    dim = d**3
    matrix_reshaped = np.array(M).reshape((d, d, d, d, d, d))
    return matrix(np.array([[[[[[matrix_reshaped[i,j,m,l,k,n] for i in range(0,d)] for j in range(0,d)] for k in range(0,d)] for l in range(0,d)] for m in range(0,d)] for n in range(0,d)]).reshape((dim ,dim)))


II) Example for $d=2$

Consider the matrix algebra $\mathcal{M}_{2}(\mathbb{C})\otimes \mathcal{M}_{2}(\mathbb{C})\otimes\mathcal{M}_{2}(\mathbb{C})$ and consider the following basis for $\mathcal{M}_{2}(\mathbb{C})$:
\begin{align}
\{ S^{i} W^{j} \}_{i,j = 0,1} \ \ \text{with} \ S = \begin{pmatrix}  0 &1 \\ 1&0 \end{pmatrix} \ \text{and} \ W= \begin{pmatrix} 1 & 0 \\ 0& \lambda  \end{pmatrix} \ \text{where} \ \lambda = \mathrm{exp}( \pi i)
\end{align}

Define three quasi-orthogonal subalgebras:
\begin{align}
\mathcal{L} \cong \mathcal{M}_{2} (\mathbb{C}) \otimes \mathbb{I}_4 &= \{ \mathbb{I}_2 \otimes \mathbb{I}_4, SW \otimes \mathbb{I}_4, W \otimes \mathbb{I}_4, S \otimes \mathbb{I}_4 \}, \\
\mathcal{R} \cong  \mathbb{I}_4 \otimes \mathcal{M}_{2} (\mathbb{C}) &= \{ \mathbb{I}_4 \otimes \mathbb{I}_2, \mathbb{I}_4 \otimes SW, \mathbb{I}_4 \otimes S,  \mathbb{I}_4 \otimes W \}, \\
\mathcal{M} \cong  \mathbb{I}_2 \otimes \mathcal{M}_{2} (\mathbb{C}) \otimes \mathbb{I}_2 &= \{ \mathbb{I}_2 \otimes \mathbb{I}_2 \otimes \mathbb{I}_2,  \mathbb{I}_2 \otimes SW \otimes \mathbb{I}_2, \mathbb{I}_2 \otimes W \otimes \mathbb{I}_2, \mathbb{I}_2 \otimes S \otimes \mathbb{I}_2\}.
\end{align}


In [43]:
# Define matrices

S_2 = M2([[0,1],[1,0]])
W_2 = M2([[1,0],[0, l]])
Id2 = identity_matrix(2)
Id4 = identity_matrix(4)
Id8 = identity_matrix(8)


# Define basis

Basis_2 = [Id2, S_2, W_2, S_2*W_2]



In [44]:
# Define local subalgebras

L_2 = [ M8(Basis_2[i].tensor_product(Id4)) for i in range(0,4) ]
R_2 = [ M8(Id4.tensor_product(Basis_2[i])) for i in range(0,4) ]
M_2 = [ M8(Id2.tensor_product(Basis_2[i].tensor_product(Id2)))for i in range(0,4) ]


# collect them in a list

LocalSubal_2 = [L_2,R_2,M_2]



The following 3-unitary matrix was taken from https://arxiv.org/pdf/1506.08857:

\begin{align}
U = \frac{1}{\sqrt{8}}
\begin{pmatrix} -1 &-1&-1&1&-1&1&1&1 \\ -1&-1&-1&1&1&-1&-1&-1\\ -1&-1&1&-1&-1&1&-1&-1 \\ 1&1&-1&1&-1&1&-1&-1 \\-1&1&-1&-1&-1&-1&1&-1 \\ 1&-1&1&1&-1&-1&1&-1\\ 1&-1&-1&-1&1&1&1&-1\\ 1&-1&-1&-1&-1&-1&-1&1
\end{pmatrix}.
\end{align}


In [48]:
# Define 3-unitary 

U = (8**(-1/2))*M8([[-1,-1,-1,1,-1,1,1,1],[-1,-1,-1,1,1,-1,-1,-1],[-1,-1,1,-1,-1,1,-1,-1],[1,1,-1,1,-1,1,-1,-1],[-1,1,-1,-1,-1,-1,1,-1],[1,-1,1,1,-1,-1,1,-1],[1,-1,-1,-1,1,1,1,-1],[1,-1,-1,-1,-1,-1,-1,1]]).transpose()


# Test 

U.is_unitary()

True

In [49]:
# U is self-adjoint

U.conjugate_transpose() == U

True

In [50]:
# U has order 2

U**2

[1 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 1]

Now use $U \in U(8)$ in order to define rotated subalgebras $\mathcal{A}_{\mathcal{L}} := U \mathcal{L} U^{\dagger}$, $\mathcal{A}_{\mathcal{R}} := U \mathcal{R} U^{\dagger}$ and $\mathcal{A}_{\mathcal{M}} := U \mathcal{M} U^{\dagger}$ that are delocalised.

In [70]:
# Define rotated subalgebras

AL_2= [M8(U*L_2[i]*U.conjugate_transpose()) for i in range(0,4)]

AR_2= [M8(U*R_2[i]*U.conjugate_transpose()) for i in range(0,4)]

AM_2= [M8(U*M_2[i]*U.conjugate_transpose()) for i in range(0,4)]

In [71]:
# Check if subalgebras are delocalised


is_delocalised(AL_2, LocalSubal_2) 

True

In [72]:
is_delocalised(AR_2, LocalSubal_2) 

True

In [73]:
is_delocalised(AM_2, LocalSubal_2) 

True

In [74]:
# Construct all possible rearrrangements of U

U_R_16 = matrix_reshuffle_16(U,2)
U_R_15 = matrix_reshuffle_15(U,2)
U_G_14 = matrix_partial_transpose_14(U,2)
U_R_24 = matrix_reshuffle_24(U,2)
U_G_25 = matrix_partial_transpose_25(U,2)
U_R_26 = matrix_reshuffle_26(U,2)
U_R_34 = matrix_reshuffle_34(U,2)
U_R_35 = matrix_reshuffle_35(U,2)
U_G_36 = matrix_partial_transpose_36(U,2)


U_reordered_2 = [U_R_16,U_R_15,U_G_14,U_R_24,U_G_25,U_R_26,U_R_34,U_R_35,U_G_36]



In [75]:
# Test if all rearrangements are unitary

for V in U_reordered_2:
    print(V.is_unitary())

True
True
True
True
True
True
True
True
True


In [76]:
# check which rearrangements are self-adjoint
# as it turns out, these are only the unitaries correpsonding to the partial transpose operations

for V in U_rearr_2:
    print(V == V.transpose())
    

False
False
True
False
True
False
False
False
True



III)

Consider the matrix algebra $\mathcal{M}_{3}(\mathbb{C}) \otimes \mathcal{M}_{3} (\mathbb{C}) \otimes \mathcal{M}_{3} (\mathbb{C})$ with the following basis:

\begin{align}
\{ S^{i} W^{j} \}_{i,j = 0,1,2} \ \ \text{with} \ S = \begin{pmatrix} 0 & 0 &1 \\ 1&0&0 \\ 0&1&0 \end{pmatrix} \ \text{and} \ W= \begin{pmatrix} 1 & 0&0 \\ 0& \lambda & 0 \\ 0&0& \lambda^{2} \end{pmatrix} \ \text{where} \ \lambda = \mathrm{exp}(2 \pi i /3)
\end{align}

The local subalgebras are given by: 

\begin{align}
\mathcal{L} \cong \mathcal{M}_{3} (\mathbb{C}) \otimes \mathbb{I}_9 &= \{ \mathbb{I}_3 \otimes \mathbb{I}_9, S \otimes \mathbb{I}_9, SW \otimes \mathbb{I}_9, S^{2}W^{2} \otimes \mathbb{I}_9, SW^{2} \otimes \mathbb{I}_9, S^{2} \otimes \mathbb{I}_9, W \otimes \mathbb{I}_9, S^{2} W \otimes \mathbb{I}_9, W^{2} \otimes \mathbb{I}_9 \}  \ \ \  \text{and} \\
\mathcal{R} \cong  \mathbb{I}_9 \otimes \mathcal{M}_{3} (\mathbb{C}) &= \{ \mathbb{I}_9 \otimes \mathbb{I}_3,\mathbb{I}_9 \otimes S, \mathbb{I}_9 \otimes SW, \mathbb{I}_9 \otimes S^{2} W^{2}, \mathbb{I}_9 \otimes SW^{2}, \mathbb{I}_9 \otimes S^{2}, \mathbb{I}_9 \otimes W, \mathbb{I}_9 \otimes S^{2}W, \mathbb{I}_9 \otimes W^{2} \}.
\end{align}
and 
\begin{align}
\mathcal{M} \cong  \mathbb{I}_3 \otimes \mathcal{M}_{3} (\mathbb{C}) \otimes \mathbb{I}_3 = \{ \mathbb{I}_3 \otimes \mathbb{I}_3 \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes S \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes SW \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes S^{2}W^{2} \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes SW^{2} \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes S^{2} \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes W \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes S^{2} W \otimes \mathbb{I}_3, \mathbb{I}_3 \otimes W^{2} \otimes \mathbb{I}_3 \}
\end{align}


In [79]:
# Define basis


S = M3([[0,0,1],[1,0,0], [0,1,0]])
W = M3([[1,0,0],[0, w,0],[0,0, w**2]])
Id3 = M3(identity_matrix(3))
Id9 =M9(identity_matrix(9))


Basis = [Id3, S, W, S**2, W**2, S*W, (S**2)*(W**2), (S**2)*W, S*(W**2)]


In [91]:
# Define subalgebras

L_3 = [ M27(Basis[i].tensor_product(Id9)) for i in range(0,9) ]
R_3 = [ M27(Id9.tensor_product(Basis[i])) for i in range(0,9) ]
M_3 = [ M27((Id3.tensor_product(Basis[i])).tensor_product(Id3)) for i in range(0,9) ]

# collect them in a list

LocalSubal = [L_3,R_3,M_3]


# Test 

is_quasi_orth(L_3,M_3)



True

In [84]:
# Define matrix from example

U_prime = (M27([
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 1, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
   0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   1, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0]]))


print(U_prime.str())

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0

In [28]:
# write matrix as permutation (for LaTeX)

perm = []
for i in range(0,27):
    for j in range(0,27):
        if U_prime[j,i] == 1:
            perm.append(j)

            
perm

[0,
 26,
 13,
 7,
 21,
 11,
 5,
 19,
 15,
 22,
 9,
 8,
 20,
 16,
 3,
 24,
 14,
 1,
 17,
 4,
 18,
 12,
 2,
 25,
 10,
 6,
 23]

In [85]:
# Check unitarity

U_prime.is_unitary()


True

In [86]:
# Check if U' is self-adjoint

U_prime == (U_prime).transpose()

False

Use $U \in U(27)$ to construct the rotated subalgebras $\mathcal{A}_{\mathcal{L}} := U \mathcal{L} U^{\dagger}$, $\mathcal{A}_{\mathcal{R}} := U \mathcal{R} U^{\dagger}$ and $\mathcal{A}_{\mathcal{M}} := U \mathcal{M} U^{\dagger}$ that are delocalised.

In [92]:
# Define delocalised subalgebra

AL_3= [Matrix(U_prime*L_3[i]*U_prime.transpose()) for i in range(0,9)]

AR_3= [Matrix(U_prime*R_3[i]*U_prime.transpose()) for i in range(0,9)]

AM_3= [Matrix(U_prime*M_3[i]*U_prime.transpose()) for i in range(0,9)]

# collect them in a list

rotated_subal = [AL_3,AR_3, AM_3]

# define a list of strings corresponding to the subalgebras in the above list

rotated_subal_str = ['AL','AR', 'AM']


In [93]:
# Test if all subalgebras are delocalised

for i in range(0,3):
        print(rotated_subal_str[i], is_delocalised(rotated_subal[i],LocalSubal))
  


AL True
AR True
AM True


In [95]:
# compute all possible rearrangments of U_prime

U_prime_R_16 = matrix_reshuffle_16(U_prime,3)
U_prime_R_15 = matrix_reshuffle_15(U_prime,3)
U_prime_G_14 = matrix_partial_transpose_14(U_prime,3)
U_prime_R_24 = matrix_reshuffle_24(U_prime,3)
U_prime_G_25 = matrix_partial_transpose_25(U_prime,3)
U_prime_R_26 = matrix_reshuffle_26(U_prime,3)
U_prime_R_34 = matrix_reshuffle_34(U_prime,3)
U_prime_R_35 = matrix_reshuffle_35(U_prime,3)
U_prime_G_36 = matrix_partial_transpose_36(U_prime,3)


# collect them in a list

U_prime_reordered = [U_prime_R_16,U_prime_R_15,U_prime_G_14,U_prime_R_24,U_prime_G_25,U_prime_R_26,U_prime_R_34,U_prime_R_35,U_prime_G_36]


# define a list of strings correpsonding to the matrices in the above list

rearr_str = ['U_R_16','U_R_15','U_G_14','U_R_24','U_G_25','U_R_26','U_R_34','U_R_35','U_G_36']


In [96]:
# Test if all rearrangements are unitary

for i in range(0,9):
    print(rearr_str[i], U_prime_reordered[i].is_unitary())

U_R_16 True
U_R_15 False
U_G_14 True
U_R_24 True
U_G_25 True
U_R_26 True
U_R_34 True
U_R_35 True
U_G_36 True


IV) Norms


In the following different norms of the rearranged matrices will be computed.


Start by calculating the partial traces of the rearranged matrices as they appear in the proof.


In [100]:
# Define qutrit basis

def unitV(i):
    vec = np.zeros(3)
    for l in range(0,3):
        if l == i:
            vec[l] = 1
    return vec

# Test 

unitV(0)

array([1., 0., 0.])

In [101]:
# Define tensor product of 2 qutrits

def unitV2(i,j):
    return np.kron(unitV(i),unitV(j))

In [102]:
# compute partial traces

U_R_16_tr2 = []
U_R_15_tr3 = []
U_G_14_tr2 = []
U_R_24_tr3 = []
U_G_25_tr3 = []
U_R_26_tr2 = []
U_R_34_tr2 = []
U_R_35_tr3 = []
U_G_36_tr2 = []

for i in range(0,3):
     for j in range(0,3):
        for k in range(0,3):
            for l in range(0,3):
                for m in range(0,3):
                    for n in range(0,3):
                        U_R_15_tr3.append(np.array(matrix(U_prime_R_15)*matrix(U_prime_R_15).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,j), unitV2(l,m))*np.trace(np.outer(unitV(k), unitV(n)))))
                        U_R_24_tr3.append(np.array(matrix(U_prime_R_24)*matrix(U_prime_R_24).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,j), unitV2(l,m))*np.trace(np.outer(unitV(k), unitV(n)))))
                        U_G_25_tr3.append(np.array(matrix(U_prime_G_25)*matrix(U_prime_G_25).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,j), unitV2(l,m))*np.trace(np.outer(unitV(k), unitV(n)))))
                        U_R_35_tr3.append(np.array(matrix(U_prime_R_35)*matrix(U_prime_R_35).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,j), unitV2(l,m))*np.trace(np.outer(unitV(k), unitV(n)))))
                        U_R_16_tr2.append(np.array(matrix(U_prime_R_16)*matrix(U_prime_R_16).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,k), unitV2(l,n))*np.trace(np.outer(unitV(j), unitV(m)))))
                        U_G_14_tr2.append(np.array(matrix(U_prime_G_14)*matrix(U_prime_G_14).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,k), unitV2(l,n))*np.trace(np.outer(unitV(j), unitV(m)))))
                        U_R_26_tr2.append(np.array(matrix(U_prime_R_26)*matrix(U_prime_R_26).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,k), unitV2(l,n))*np.trace(np.outer(unitV(j), unitV(m)))))
                        U_R_34_tr2.append(np.array(matrix(U_prime_R_34)*matrix(U_prime_R_34).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,k), unitV2(l,n))*np.trace(np.outer(unitV(j), unitV(m)))))
                        U_G_36_tr2.append(np.array(matrix(U_prime_G_36)*matrix(U_prime_G_36).transpose()).reshape(3,3,3,3,3,3)[i,j,k,l,m,n]*(np.outer(unitV2(i,k), unitV2(l,n))*np.trace(np.outer(unitV(j), unitV(m)))))
                        


# collect the resulting matrices in a a list

rearr_PT = [matrix(sum(U_G_36_tr2).reshape(9,9)),matrix(sum(U_R_34_tr2).reshape(9,9)), matrix(sum(U_R_26_tr2).reshape(9,9)), matrix(sum(U_G_14_tr2).reshape(9,9)), matrix(sum(U_R_16_tr2).reshape(9,9)), matrix(sum(U_R_35_tr3).reshape(9,9)),matrix(sum(U_G_25_tr3).reshape(9,9)),matrix(sum(U_R_24_tr3).reshape(9,9)),matrix(sum(U_R_15_tr3).reshape(9,9))]                       

In [103]:
# define a function that computes the 2-norm

def TwoNorm(A, d):
    list = []
    for i in range(0,d):
        for j in range(0,d):
            list.append(abs(A[i,j])**2)
    return sum(list)

In [104]:
# compute 2-norms of rearrangements of U'

for i in range(0,9):
    print(rearr_str[i], (TwoNorm(U_prime_reordered[i]*(U_prime_reordered[i].transpose()),27))/27)
    

U_R_16 1
U_R_15 9
U_G_14 1
U_R_24 1
U_G_25 1
U_R_26 1
U_R_34 1
U_R_35 1
U_G_36 1


In [119]:
# compute Schatten 2-norm of U' itself

TwoNorm(U_prime,27 )

27

In [106]:
# compute 2 norm of partial traces
    
for i in range(0,9):
    print((TwoNorm(rearr_PT[i],9))/81)
    

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [107]:
# define function that computes schatten 4-norm

def SchFourNorm(A):
    list = (A**2).eigenvalues()
    list2 = []
    for i in list:
        list2.append(abs(i))
    return (sum(list2))

In [109]:
# compute schatten 4-norm of rearrangments of U'

for i in range(0,9):
    print(rearr_str[i], ((SchFourNorm(U_prime_reordered[i]*U_prime_reordered[i].transpose())))/27)
    

U_R_16 1
U_R_15 9
U_G_14 1
U_R_24 1
U_G_25 1
U_R_26 1
U_R_34 1
U_R_35 1
U_G_36 1


In [118]:
# compute Schatten 4-norm of U' itself

SchFourNorm(U_prime)

27.00000000000000?

In [110]:
# define function that computes schatten 4-norm

def SchTwoNorm(A):
    list = []
    l = A.eigenvalues()
    for i in l:
        list.append(abs(i))
    return sum(list)

In [111]:
# compute schatten 2-norms of rearrengments of U'

for i in range(0,9):
            print(rearr_str[i], ((SchTwoNorm(U_prime_reordered[i]*U_prime_reordered[i].transpose()))**2)/(27**2))
    

U_R_16 1
U_R_15 1
U_G_14 1
U_R_24 1
U_G_25 1
U_R_26 1
U_R_34 1
U_R_35 1
U_G_36 1


In [117]:
# compute Schatten 2-norm of U' itself

SchTwoNorm(U_prime)

27.00000000000000?